input:
  file:
    paths:
      - ./message.json
    scanner:
      json_documents: {}

pipeline:
  processors:
    - mapping: |
        let now = now()

        root.id = this.id
        root.processed_at = $now
        root.item_count = this.items.length()

        map item_map {
          let key = this.name.
            trim().
            lowercase().
            re_replace_all("[\\s]+", "_")

          root = {
            $key: this.description
          }
        }

        root.items = this.items.
          map_each(i -> i.apply("item_map")).
          squash()

        root.now = $now
        root.now_sub_one_hour = $now.ts_sub_iso8601("PT1H")
        root.now_add_one_hour = $now.ts_add_iso8601("PT1H")

    - mapping: |
        root = this.format_json()

output:
  file:
    path: ./message.processed.json
    codec: all-bytes
