input:
  generate:
    mapping: root = {}
    interval: 0/10 * * * * *

pipeline:
  processors:
    - mapping: |
        root = this
        root.processed_on = hostname()
        root.processed_at = now()
        root.processed_by = "demo-pipeline"

output:
  stdout: {}

http:
  address: ${HTTP_ADDRESS}

logger:
  level: ${LOG_LEVEL:INFO}
  format: logfmt
  static_fields:
    service: demo-pipeline

tracer:
  open_telemetry_collector:
    grpc:
      - address: ${OPEN_TELEMETRY_COLLECTOR_GRPC_ADDRESS}

shutdown_delay: 5s
