receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets: [localhost:8080]

exporters:
  azuremonitor:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor]
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [azuremonitor]
