input:
  opcua:
    endpoint: "opc.tcp://uademo.prosysopc.com:53530"
    nodeIDs:
      - ns=3;i=1001
      - ns=3;i=1003
    # username: "your-username" # optional (default: unset)
    # password: "your-password" # optional (default: unset)
    # insecure: false | true # DEPRECATED, see below
    # securityMode: None | Sign | SignAndEncrypt # optional (default: unset)
    # securityPolicy: None | Basic256Sha256 # optional (default: unset)
    # subscribeEnabled: false | true # optional (default: false)
    # useHeartbeat: false | true # optional (default: false)
    pollRate: 5000 # optional (default: 1000) The rate in milliseconds at which to poll the OPC UA server when not using subscriptions
    # autoReconnect: false | true # optional (default: false)
    # reconnectIntervalInSeconds: 5 # optional (default: 5) The rate in seconds at which to reconnect to the OPC UA server when the connection is lost

pipeline:
  processors:
    - mapping: |
        root.data = this
        root.metadata = metadata()

output:
  file:
    path: ./message.processed.jsonl
