receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:RECEIVER_GRPC_ENDPOINT}

  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets:
                - ${env:DEMO_PIPELINE_HTTP_ADDRESS}

exporters:
  azuremonitor:
    connection_string: ${env:APPLICATIONINSIGHTS_CONNECTION_STRING}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [azuremonitor]
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [azuremonitor]
